title: My Github Page
author: Alezco
email: benjamin.morali@epita.fr
description: > # this means to ignore newlines until "baseurl:"
  Welcome here!

# social links
twitter_username: Alezco_
github_username:  Alezco

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
